thresholds:
  model_alert: 0.80          # anomaly probability above which to alert
  rules_alert: 2             # number of triggered rules to bump severity
business_hours:
  start: 8
  end: 18
high_risk_countries: ["RU", "KP", "IR", "CN"]
geo_jump_km: 1200
large_transfer_amount: 75000
privileged_roles: ["admin", "ops", "supervisor"]
