# .github/workflows/e2e.yml
name: e2e-tests-and-allure

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

permissions:                # <-- required for Pages
  contents: read
  pages: write
  id-token: write

concurrency:                # optional but recommended for Pages
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}            # set this if you don’t start a local app
      QTEST_BASE_URL: ${{ secrets.QTEST_BASE_URL }}  # (optional)
      QTEST_PROJECT_ID: ${{ secrets.QTEST_PROJECT_ID }}
      QTEST_TOKEN: ${{ secrets.QTEST_TOKEN }}
      QTEST_RELEASE_ID: ${{ secrets.QTEST_RELEASE_ID }}
      QTEST_TEST_CYCLE_ID: ${{ secrets.QTEST_TEST_CYCLE_ID }}
      QTEST_TEST_SUITE_ID: ${{ secrets.QTEST_TEST_SUITE_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install test deps
        working-directory: ./selenium-pytest-bdd-allure-qtest-ci
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-xdist

      # Optional: start your Flask app locally if BASE_URL is not provided
      - name: Start local Flask app (optional)
        if: env.BASE_URL == ''
        run: |
          echo "[CI] No BASE_URL provided; trying to start local app on 127.0.0.1:5010"
          if [ -f "requirements.txt" ]; then
            python -m pip install -r requirements.txt || true
          fi
          # If you use the rbc-security-insights-ai subfolder, uncomment to auto-start it:
          if [ -d "rbc-security-insights-ai" ]; then
            pushd rbc-security-insights-ai
            python -m pip install -r requirements.txt
            python -m core.synth --days 2 --users 60 --out data/events.csv
            python -m pipelines.train --in data/events.csv --model_dir models
            python -m pipelines.score --in data/events.csv --model_dir models --out data/insights.csv
            nohup python -m app.app > rbc_app.log 2>&1 &
            popd
          elif [ -f "app/app.py" ]; then
            nohup python -m app.app > app.log 2>&1 &
          fi
          for i in $(seq 1 60); do
            curl -fsS http://127.0.0.1:5010/health && break || true
            sleep 1
          done

      - name: Run tests (parallel) → Allure results
        working-directory: ./selenium-pytest-bdd-allure-qtest-ci
        run: |
          mkdir -p reports/allure-results
          BASE="${BASE_URL:-http://127.0.0.1:5010}"
          echo "Using BASE_URL=$BASE"
          pytest -n auto --base-url "$BASE" || true

      - name: Upload raw Allure results (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: selenium-pytest-bdd-allure-qtest-ci/reports/allure-results

      - name: Install Allure CLI
        run: |
          ALLURE_VER=2.27.0
          curl -sL -o allure.tgz https://github.com/allure-framework/allure2/releases/download/${ALLURE_VER}/allure-${ALLURE_VER}.tgz
          tar -xzf allure.tgz
          echo "$PWD/allure-${ALLURE_VER}/bin" >> $GITHUB_PATH

      - name: Generate Allure HTML
        working-directory: ./selenium-pytest-bdd-allure-qtest-ci
        run: |
          allure generate reports/allure-results -o allure-report --clean || echo "Allure generation failed"

      - name: Install wkhtmltopdf (for PDF)
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Export Allure → PDF (best-effort)
        working-directory: ./selenium-pytest-bdd-allure-qtest-ci
        run: |
          if [ -f allure-report/index.html ]; then
            wkhtmltopdf --disable-smart-shrinking allure-report/index.html allure-report.pdf || echo "wkhtmltopdf failed"
          fi

      - name: Upload Allure HTML + PDF (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: |
            selenium-pytest-bdd-allure-qtest-ci/allure-report
            selenium-pytest-bdd-allure-qtest-ci/allure-report.pdf

      - name: Prepare Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: selenium-pytest-bdd-allure-qtest-ci/allure-report   # <— this becomes the website

      - name: Push results to qTest (optional)
        if: env.QTEST_BASE_URL != '' && env.QTEST_PROJECT_ID != '' && env.QTEST_TOKEN != ''
        working-directory: ./selenium-pytest-bdd-allure-qtest-ci
        run: |
          python qtest_integration/qtest_push.py reports/allure-results || echo "qTest push failed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
